# Generated by Django 2.2.11 on 2020-04-11 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='lugar_compra_idlugar_compra',
            new_name='fk_lugar_compra',
        ),
        migrations.AlterField(
            model_name='lugarcompra',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lugarcompra',
            name='nombre_tienda',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('registroid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_anterior', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('hora', models.TimeField(default=django.utils.timezone.now, editable=False)),
                ('articulo_idarticulo', models.ForeignKey(db_column='articulo_idarticulo', on_delete=django.db.models.deletion.DO_NOTHING, to='lavado.Articulo')),
            ],
        ),
    ]
