# Generated by Django 3.0.3 on 2020-03-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('registroid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_anterior', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('articulo_idarticulo', models.ForeignKey(db_column='articulo_idarticulo', on_delete=django.db.models.deletion.DO_NOTHING, to='lavado.Articulo')),
            ],
        ),
    ]
