# Generated by Django 3.0.3 on 2020-03-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0002_registroinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarcompra',
            name='direccion',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='lugarcompra',
            name='nombre_tienda',
            field=models.CharField(max_length=30),
        ),
    ]
