# Generated by Django 3.0.3 on 2020-03-06 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0004_auto_20200306_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='lugar_compra_idlugar_compra',
            new_name='fk_lugar_compra',
        ),
        migrations.AlterField(
            model_name='registroinventario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='registroinventario',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
